// <auto-generated />
using System;
using CodeProject.InventoryManagement.Data.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeProject.InventoryManagement.Data.EntityFramework.Migrations
{
    [DbContext(typeof(InventoryManagementDatabase))]
    [Migration("20180911232521_transactionqueueing")]
    partial class transactionqueueing
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeProject.InventoryManagement.Data.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId");

                    b.Property<double>("AverageCost");

                    b.Property<string>("BinLocation");

                    b.Property<int>("CommittedQuantity");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<string>("Description");

                    b.Property<int>("OnHandQuantity");

                    b.Property<int>("OnOrderQuantity");

                    b.Property<string>("ProductNumber");

                    b.Property<double>("UnitPrice");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductNumber");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CodeProject.InventoryManagement.Data.Entities.TransactionQueueInbound", b =>
                {
                    b.Property<int>("TransactionQueueInboundId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("ExchangeName");

                    b.Property<string>("Payload");

                    b.Property<int>("SenderTransactionQueueId");

                    b.Property<string>("TransactionCode");

                    b.HasKey("TransactionQueueInboundId");

                    b.ToTable("TransactionQueueInbound");
                });

            modelBuilder.Entity("CodeProject.InventoryManagement.Data.Entities.TransactionQueueInboundHistory", b =>
                {
                    b.Property<int>("TransactionQueueInboundHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateCreatedInbound");

                    b.Property<bool>("DuplicateMessage");

                    b.Property<string>("ErrorMessage");

                    b.Property<string>("ExchangeName");

                    b.Property<string>("Payload");

                    b.Property<bool>("ProcessedSuccessfully");

                    b.Property<int>("SenderTransactionQueueId");

                    b.Property<string>("TransactionCode");

                    b.Property<int>("TransactionQueueInboundId");

                    b.HasKey("TransactionQueueInboundHistoryId");

                    b.ToTable("TransactionQueueInboundHistory");
                });

            modelBuilder.Entity("CodeProject.InventoryManagement.Data.Entities.TransactionQueueOutbound", b =>
                {
                    b.Property<int>("TransactionQueueOutboundId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateSentToExchange");

                    b.Property<DateTime>("DateToResendToExchange");

                    b.Property<string>("ExchangeName");

                    b.Property<string>("Payload");

                    b.Property<bool>("SentToExchange");

                    b.Property<string>("TransactionCode");

                    b.HasKey("TransactionQueueOutboundId");

                    b.ToTable("TransactionQueueOutbound");
                });

            modelBuilder.Entity("CodeProject.InventoryManagement.Data.Entities.TransactionQueueOutboundHistory", b =>
                {
                    b.Property<int>("TransactionQueueOutboundHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateOutboundTransactionCreated");

                    b.Property<DateTime>("DateSentToExchange");

                    b.Property<DateTime>("DateToResendToExchange");

                    b.Property<string>("ExchangeName");

                    b.Property<string>("Payload");

                    b.Property<bool>("SentToExchange");

                    b.Property<string>("TransactionCode");

                    b.Property<int>("TransactionQueueOutboundId");

                    b.HasKey("TransactionQueueOutboundHistoryId");

                    b.ToTable("TransactionQueueOutboundHistory");
                });

            modelBuilder.Entity("CodeProject.InventoryManagement.Data.Entities.TransactionQueueSemaphore", b =>
                {
                    b.Property<int>("TransactionQueueSemaphoreId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<string>("SemaphoreKey");

                    b.HasKey("TransactionQueueSemaphoreId");

                    b.HasIndex("SemaphoreKey")
                        .IsUnique()
                        .HasFilter("[SemaphoreKey] IS NOT NULL");

                    b.ToTable("TransactionQueueSemaphores");
                });
#pragma warning restore 612, 618
        }
    }
}
