// <auto-generated />
using System;
using CodeProject.InventoryManagement.Data.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeProject.InventoryManagement.Data.EntityFramework.Migrations
{
    [DbContext(typeof(InventoryManagementDatabase))]
    partial class InventoryManagementDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeProject.InventoryManagement.Data.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId");

                    b.Property<double>("AverageCost");

                    b.Property<string>("BinLocation");

                    b.Property<int>("CommittedQuantity");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<string>("Description");

                    b.Property<int>("OnHandQuantity");

                    b.Property<int>("OnOrderQuantity");

                    b.Property<string>("ProductNumber");

                    b.Property<double>("UnitPrice");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductNumber");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CodeProject.InventoryManagement.Data.Entities.TransactionQueue", b =>
                {
                    b.Property<int>("TransactionQueueId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateSentToExchange");

                    b.Property<DateTime>("DateToResendToExchange");

                    b.Property<string>("ExchangeName");

                    b.Property<string>("Payload");

                    b.Property<bool>("SentToExchange");

                    b.Property<string>("TransactionCode");

                    b.HasKey("TransactionQueueId");

                    b.ToTable("TransactionQueue");
                });
#pragma warning restore 612, 618
        }
    }
}
