// <auto-generated />
using MicroServicesTest.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MicroServicesTest.Migrations
{
    [DbContext(typeof(StockDatabase))]
    [Migration("20180819213741_InitialDatabase")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MicroServicesTest.Models.ProductPart", b =>
                {
                    b.Property<int>("ProductPartId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("ProductNumber");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("ProductPartId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("MicroServicesTest.Models.StockPart", b =>
                {
                    b.Property<int>("StockPartId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProductNumber");

                    b.Property<int>("QuantityOnHand");

                    b.Property<int>("QuantityOnOrder");

                    b.HasKey("StockPartId");

                    b.ToTable("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
